"use client";

// What a box is likely to earn, and why.
//
// This is the one place in the app that still explains itself at length, and
// it earns that: it is a number somebody is about to put a million naira
// behind. Everything else has been cut back to a line. Even here the workings
// are collapsed behind a tap, because a contributor who has already decided
// shouldn't have to scroll past the arithmetic to get to the button.
//
// It is always quoted per thousand hunters. Quoting a live box's real player
// count looked more precise and was useless — a box with four hunters
// projected four hunters' worth of income, which says nothing about whether
// the box is worth running. A rate is the thing a contributor can multiply by
// their own expectations. What the box has *actually* made sits beside it, so
// the projection is never confused with the takings.

import { useState } from "react";
import { ChevronDown, TrendingUp } from "lucide-react";
import { formatNaira } from "@/lib/game/rewards";
import { BASIS, revenueRange, SPENDING_SHARE } from "@/lib/game/revenue";
import { plural } from "@/lib/plural";

export function RevenueEstimate({
  rewardKobo,
  hunters,
  earnedKobo,
}: {
  /** What's behind the password. The whole shelf is priced off it. */
  rewardKobo: number;
  /** Real hunters so far. Shown as fact, never used as the projection basis. */
  hunters: number;
  earnedKobo: number;
}) {
  const [open, setOpen] = useState(false);
  const range = revenueRange(rewardKobo);

  return (
    <div className="rounded-xl bg-white/5 p-4">
      <p className="flex items-center gap-1.5 text-xs uppercase tracking-wide text-zinc-500">
        <TrendingUp className="size-3.5" aria-hidden />
        Estimated Earnings per {BASIS.toLocaleString("en-NG")} Hunters
      </p>
      <p className="mt-1 font-mono text-xl font-bold text-brass">
        {formatNaira(range.lowKobo)} – {formatNaira(range.highKobo)}
      </p>

      <p className="mt-2 text-xs text-zinc-500">
        {earnedKobo > 0
          ? `${formatNaira(earnedKobo)} earned so far from ${plural(hunters, "hunter")}.`
          : hunters > 0
            ? `${plural(hunters, "hunter")} so far, nothing bought yet.`
            : "No hunters yet."}
      </p>

      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className="mt-3 flex items-center gap-1.5 text-xs font-medium text-zinc-400 transition hover:text-zinc-200"
      >
        <ChevronDown
          className={"size-3.5 transition " + (open ? "rotate-180" : "")}
          aria-hidden
        />
        How These Estimates Are Calculated
      </button>

      {open && (
        <div className="mt-3 space-y-3 border-t border-white/5 pt-3 text-xs leading-relaxed text-zinc-400">
          <p>
            You keep{" "}
            <strong className="text-zinc-200">{range.sharePercent}%</strong> of all
            spending generated by your Spendbox, including power-ups and extra
            lives. Spendbox retains the remaining {100 - range.sharePercent}%.
          </p>

          <p>
            Power-up prices scale with the value of your reward, so potential
            earnings increase as the reward increases. On a Spendbox with a{" "}
            {formatNaira(range.rewardKobo)} reward, the cheapest power-up is{" "}
            {formatNaira(range.cheapestKobo)} and the whole shelf comes to{" "}
            {formatNaira(range.fullShelfKobo)}.
          </p>

          <p>
            Because every Spendbox behaves differently, these figures are not
            predictions — they’re scenarios designed to help you understand
            the earning potential of your box.
          </p>

          <p>
            Our model assumes that out of every{" "}
            {range.hunters.toLocaleString("en-NG")} hunters, around{" "}
            {range.spenders.toLocaleString("en-NG")} make at least one purchase
            ({Math.round(SPENDING_SHARE * 100)}%).
          </p>

          <ul className="space-y-1.5">
            <li className="flex gap-2">
              <span aria-hidden>–</span>
              <span>
                <strong className="text-zinc-200">Conservative scenario:</strong>{" "}
                each paying hunter purchases only the lowest-priced power-up.
              </span>
            </li>
            <li className="flex gap-2">
              <span aria-hidden>–</span>
              <span>
                <strong className="text-zinc-200">
                  High-engagement scenario:
                </strong>{" "}
                each paying hunter purchases every available power-up and an
                additional {range.livesPerSpender} lives.
              </span>
            </li>
          </ul>

          <p>
            The actual outcome depends on factors such as the difficulty of your
            password, the attractiveness of the reward, and the number of people
            who discover your Spendbox. Harder challenges often keep hunters
            engaged for longer, increasing the likelihood of additional
            purchases.
          </p>

          <p className="text-zinc-500">
            These estimates represent earnings from hunter activity only. The
            reward you fund is not included, as it is paid out to the hunter who
            successfully unlocks the Spendbox.
          </p>
        </div>
      )}
    </div>
  );
}
