-- Who else is on this safe, and the things that fall out of the sky.
--
-- Two features, one migration, because both are reads the play screen makes on
-- every load and both were otherwise a query nobody should be running there.
--
-- 1. **Rivals.** The chase now shows the top ten hunters on a box as a field of
--    cars, ordered by how close each of them is. That needs one number per
--    player per box — their best score — and getting it by scanning `attempts`
--    would be a sort over every guess ever made against a popular safe, ten
--    times a page load. It is a column on `hunts` instead, moved forward by
--    `spend_attempt` with `greatest`, exactly as `boxes.best_percent` already
--    is.
--
-- 2. **Drops.** A free-lives or discount offer, minted for one player, claimed
--    once. It has to be a row rather than a browser-side coupon for the obvious
--    reason: a discount the client names is a discount the client can name
--    itself.

-- ---------------------------------------------------------------------------
-- 1. A hunt's best score
-- ---------------------------------------------------------------------------

alter table public.hunts
  add column if not exists best_percent numeric(5,2) not null default 0
  check (best_percent >= 0 and best_percent <= 100);

-- The leaderboard read: highest first, within one box.
create index if not exists hunts_box_best_idx
  on public.hunts (box_id, best_percent desc);

update public.hunts h
   set best_percent = coalesce(top.score, 0)
  from (
    select hunt_id, max(score_percent) as score from public.attempts group by hunt_id
  ) top
 where top.hunt_id = h.id and h.best_percent < coalesce(top.score, 0);

-- ---------------------------------------------------------------------------
-- 2. Drops
-- ---------------------------------------------------------------------------

/*
 * One offer, for one player.
 *
 * `kind` says what it is and `amount` is read against it: for `free_lives` it
 * is a count, for `power_up_discount` it is a percentage off. `power_up` is set
 * only for a discount, and names which one it applies to — an offer that
 * applies to whatever you happen to buy next is a coupon, and a coupon can be
 * spent on the most expensive thing on the shelf.
 *
 * Offers expire. One that sits in a drawer forever is a liability with no end
 * date, and the whole point of a drop is that it is *now*.
 */
create table if not exists public.player_offers (
  id uuid primary key default gen_random_uuid(),
  player_id uuid not null references public.players (id) on delete cascade,
  kind text not null check (kind in ('free_lives', 'power_up_discount')),
  amount int not null check (amount > 0 and amount <= 100),
  power_up text,
  /** Set for a discount: the box it was minted against. */
  box_id uuid references public.boxes (id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  claimed_at timestamptz,
  /** Set when a discount has actually been spent on an order. */
  spent_at timestamptz,
  constraint player_offers_discount_names_one
    check (kind <> 'power_up_discount' or power_up is not null)
);

alter table public.player_offers enable row level security;

-- The two reads: a player's live offers, and the one being spent at checkout.
create index if not exists player_offers_live_idx
  on public.player_offers (player_id, expires_at desc)
  where claimed_at is null;

create index if not exists player_offers_claimed_idx
  on public.player_offers (player_id, power_up, box_id)
  where claimed_at is not null and spent_at is null;

/*
 * Mint one, unless there is already one waiting.
 *
 * The "unless" is the whole function. A drop is generated by the browser
 * noticing a moment — you are low on lives, or five guesses have gone nowhere —
 * and a browser that can ask twice will. One unclaimed offer at a time, per
 * player, full stop.
 */
create or replace function public.mint_offer(
  p_email citext,
  p_kind text,
  p_amount int,
  p_power_up text default null,
  p_box_id uuid default null,
  p_minutes int default 10
)
returns public.player_offers
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player public.players;
  v_offer public.player_offers;
begin
  v_player := public.ensure_player(p_email);

  select * into v_offer from public.player_offers
   where player_id = v_player.id and claimed_at is null and expires_at > now()
   limit 1;
  if found then
    return v_offer;
  end if;

  insert into public.player_offers (player_id, kind, amount, power_up, box_id, expires_at)
  values (
    v_player.id, p_kind, p_amount,
    case when p_kind = 'power_up_discount' then p_power_up else null end,
    p_box_id,
    now() + make_interval(mins => greatest(1, p_minutes))
  )
  returning * into v_offer;

  return v_offer;
end;
$$;

/*
 * Claim one.
 *
 * Free lives land immediately — there is nothing to check out, and a free thing
 * that takes you to a payment screen is not free. A discount is only *marked*
 * claimed here; it is spent later, by the power-up route, when an order that
 * uses it is actually created.
 *
 * The update is conditional on `claimed_at is null`, so two taps race to one
 * winner and the second gets nothing back.
 */
create or replace function public.claim_offer(p_email citext, p_offer_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player public.players;
  v_offer public.player_offers;
begin
  v_player := public.ensure_player(p_email);

  update public.player_offers
     set claimed_at = now()
   where id = p_offer_id
     and player_id = v_player.id
     and claimed_at is null
     and expires_at > now()
  returning * into v_offer;

  if not found then
    return jsonb_build_object('result', 'error', 'error', 'offer_gone');
  end if;

  if v_offer.kind = 'free_lives' then
    -- Free lives may exceed the cap, exactly as bought ones do: they were
    -- given, not accrued, and clamping a gift to a ceiling is a way of taking
    -- part of it back.
    update public.players
       set lives = lives + v_offer.amount
     where id = v_player.id
    returning * into v_player;

    return jsonb_build_object(
      'result', 'claimed',
      'kind', v_offer.kind,
      'amount', v_offer.amount,
      'lives', v_player.lives
    );
  end if;

  return jsonb_build_object(
    'result', 'claimed',
    'kind', v_offer.kind,
    'amount', v_offer.amount,
    'power_up', v_offer.power_up
  );
end;
$$;

/*
 * The discount a player may use on this power-up, on this box, right now.
 *
 * Read by the checkout route immediately before it prices an order, and by
 * nothing else. Returns 0 when there isn't one, so the caller can multiply
 * without branching.
 */
create or replace function public.discount_for(
  p_player_id uuid,
  p_power_up text,
  p_box_id uuid
)
returns int
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(max(amount), 0)
    from public.player_offers
   where player_id = p_player_id
     and kind = 'power_up_discount'
     and power_up = p_power_up
     and (box_id is null or box_id = p_box_id)
     and claimed_at is not null
     and spent_at is null
     and expires_at > now();
$$;

/** Burn it, once the order that used it exists. */
create or replace function public.spend_discount(
  p_player_id uuid,
  p_power_up text,
  p_box_id uuid
)
returns void
language sql
security definer
set search_path = public
as $$
  update public.player_offers
     set spent_at = now()
   where id = (
     select id from public.player_offers
      where player_id = p_player_id
        and kind = 'power_up_discount'
        and power_up = p_power_up
        and (box_id is null or box_id = p_box_id)
        and claimed_at is not null
        and spent_at is null
        and expires_at > now()
      order by amount desc
      limit 1
   );
$$;

-- ---------------------------------------------------------------------------
-- Scoring, now also moving the hunt's high-water mark
-- ---------------------------------------------------------------------------

create or replace function public.spend_attempt(
  p_email citext,
  p_box_id uuid,
  p_guess text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player public.players;
  v_box public.boxes;
  v_hunt public.hunts;
  v_score record;
  v_ordinal int;
  v_won boolean;
  v_claimed jsonb;
  v_free boolean;
  v_wind timestamptz;
begin
  v_player := public.ensure_player(p_email);

  select * into v_box from public.boxes where id = p_box_id;
  if not found then
    return jsonb_build_object('result', 'error', 'error', 'box_not_found');
  end if;
  if v_box.status = 'unlocked' then
    return jsonb_build_object('result', 'error', 'error', 'box_unlocked');
  end if;
  if v_box.status <> 'live' then
    return jsonb_build_object('result', 'error', 'error', 'box_not_live');
  end if;

  insert into public.hunts (box_id, player_id) values (p_box_id, v_player.id)
    on conflict (box_id, player_id) do nothing;
  select * into v_hunt from public.hunts
    where box_id = p_box_id and player_id = v_player.id for update;

  if v_hunt.won_at is not null then
    return jsonb_build_object('result', 'error', 'error', 'already_won');
  end if;

  v_wind := public.second_wind_until(v_hunt.revealed);
  v_free := v_wind is not null and v_wind > now();

  if not v_free then
    if v_player.lives < 1 then
      return jsonb_build_object(
        'result', 'error',
        'error', 'no_lives',
        'next_life_at', v_player.lives_accrued_at + public.life_regen()
      );
    end if;

    update public.players set lives = lives - 1
      where id = v_player.id returning * into v_player;
  end if;

  select * into v_score from public.score_attempt(v_box.secret, p_guess);
  v_won := (p_guess = v_box.secret);
  v_ordinal := v_hunt.attempts_count;

  insert into public.attempts (
    hunt_id, ordinal, value, length_hint,
    exact_count, miscase_count, elsewhere_count, score_percent
  )
  values (
    v_hunt.id, v_ordinal, p_guess, v_score.length_hint,
    v_score.exact_count, v_score.miscase_count, v_score.elsewhere_count,
    v_score.score_percent
  );

  update public.hunts
     set attempts_count = v_ordinal + 1,
         last_attempt_at = now(),
         best_percent = greatest(best_percent, v_score.score_percent),
         won_at = case when v_won then now() else won_at end
   where id = v_hunt.id;

  update public.boxes
     set attempts_count = attempts_count + 1,
         players_count = players_count + case when v_ordinal = 0 then 1 else 0 end,
         best_percent = greatest(best_percent, v_score.score_percent)
   where id = p_box_id;

  if v_won then
    v_claimed := public.claim_box(v_hunt.id);
  end if;

  return jsonb_build_object(
    'result', 'scored',
    'length_hint', v_score.length_hint,
    'score_percent', v_score.score_percent,
    'lives_left', v_player.lives,
    'free', v_free,
    'second_wind_until', v_wind,
    'outcome', coalesce(v_claimed->>'result', 'open'),
    'reward_kobo', v_claimed->'reward_kobo'
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Privileges
-- ---------------------------------------------------------------------------

-- CREATE OR REPLACE restores the default EXECUTE grant to PUBLIC every time.
revoke execute on function
  public.spend_attempt(citext, uuid, text),
  public.mint_offer(citext, text, int, text, uuid, int),
  public.claim_offer(citext, uuid),
  public.discount_for(uuid, text, uuid),
  public.spend_discount(uuid, text, uuid)
from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Tell PostgREST
-- ---------------------------------------------------------------------------

notify pgrst, 'reload schema';
